/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author ANGEL
 */
import Clases.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class CompraMaterial extends javax.swing.JFrame {

    /**
     * Creates new form Pagos
     */
    Controles ct = new Controles();
    Controlador control = new Controlador();
    LoginAcceso acceso = new LoginAcceso();

    DefaultTableModel modelo = new DefaultTableModel();

    public CompraMaterial() {
        this.setUndecorated(true);
        initComponents();
        this.setTitle("Registro Compra");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(CompraMaterial.HIDE_ON_CLOSE);
        DatosUsuario();
        LlenarCombo();
        InicializarTabla();
        MostrarReservas();
    }

    public void DatosUsuario() {
        lbnomEmp.setText("USUARIO: " + ct.empleado);
    }

    public void LlenarCombo() {
        control.LlenarComboTit(cbomaterial, "Select * from tipomaterial ", 2);
        control.LlenarCombo(cbomarca, "select * from marcas", 2);
        control.LlenarCombo(cbocolor, "Select * from colormaterial", 2);
        control.LlenarCombo(cbofacultad, "Select * from facultades", 2);
    }

    public void InicializarTabla() {
        modelo.setColumnIdentifiers(new String[]{"ID", "FECHA", "CANTIDAD", "MATERIAL", "MARCA", "COLOR", "FACULTAD"});
        tabla.setModel(modelo);
    }

    public void MostrarReservas() {
        control.LlenarJtable(modelo, "SELECT * FROM vw_compramaterial v;", 7);
    }

    public void Crear() {
        JOptionPane.showMessageDialog(null, control.DevolverRegistroDto("call proc_materialcompra (1,'"
                + cbomaterial.getSelectedItem() + "','" + cbomarca.getSelectedItem() + "', '" + cbocolor.getSelectedItem()
                + "','" + cbofacultad.getSelectedItem() + "', " + txtcantidad.getText() + ",'" + ct.usuario + "');", 1));
        MostrarReservas();
        StockxMat();
    }

    /* public void Seleccionar() {
        int fila = tabla.getSelectedRow();
        String doc = tabla.getValueAt(fila, 5).toString();
        if (tabla.getSelectedRow() > -1) {
            txtdni.setText(tabla.getValueAt(fila, 5).toString());
            txtnom.setText(control.DevolverRegistroDto("Select nomb from personas where DNI='" + doc + "';", 1));
            txtapaterno.setText(control.DevolverRegistroDto("Select apPat from personas where DNI='" + doc + "';", 1));
            txtamaterno.setText(control.DevolverRegistroDto("Select apMat from personas where DNI='" + doc + "';", 1));
            horaE.setValue(tabla.getValueAt(fila, 2));
            minE.setValue(tabla.getValueAt(fila, fila));
        }
    }
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbcerrar = new javax.swing.JLabel();
        lbminimizar = new javax.swing.JLabel();
        lbnomEmp = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        cbofacultad = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cbomaterial = new javax.swing.JComboBox<>();
        cbomarca = new javax.swing.JComboBox<>();
        cbocolor = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        lbstock = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btcancelar = new javax.swing.JButton();
        btregistrar = new javax.swing.JButton();
        bteditar = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabelDNI16 = new javax.swing.JLabel();
        txBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COMPRA MATERIALES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 40));

        lbcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/cerrar1.png"))); // NOI18N
        lbcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbcerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbcerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbcerrarMouseExited(evt);
            }
        });
        jPanel1.add(lbcerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1335, 5, -1, -1));

        lbminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/minimizar1.png"))); // NOI18N
        lbminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbminimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbminimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbminimizarMouseExited(evt);
            }
        });
        jPanel1.add(lbminimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1305, 5, -1, -1));

        lbnomEmp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbnomEmp.setForeground(new java.awt.Color(255, 255, 255));
        lbnomEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbnomEmp.setText("NOMBRES: ANGEL PAGOLA");
        jPanel1.add(lbnomEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 400, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 40));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)), "DATOS GENERALES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbofacultad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbofacultad.setForeground(new java.awt.Color(0, 0, 0));
        cbofacultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel7.add(cbofacultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 300, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("MATERIAL:");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("COLOR:");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 30));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("FACULTAD:");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 30));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("MARCA:");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 30));

        cbomaterial.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbomaterial.setForeground(new java.awt.Color(0, 0, 0));
        cbomaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbomaterial.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbomaterialItemStateChanged(evt);
            }
        });
        jPanel7.add(cbomaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 300, 30));

        cbomarca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbomarca.setForeground(new java.awt.Color(0, 0, 0));
        cbomarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel7.add(cbomarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 300, 30));

        cbocolor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbocolor.setForeground(new java.awt.Color(0, 0, 0));
        cbocolor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel7.add(cbocolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 300, 30));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("CANTIDAD:");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 30));

        txtcantidad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtcantidad.setForeground(new java.awt.Color(0, 0, 0));
        txtcantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 300, 30));

        lbstock.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbstock.setForeground(new java.awt.Color(0, 0, 0));
        lbstock.setText("0");
        jPanel7.add(lbstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, 30));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("STOCK:");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 30));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 500, 370));

        btcancelar.setBackground(new java.awt.Color(255, 153, 0));
        btcancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btcancelar.setForeground(new java.awt.Color(0, 0, 0));
        btcancelar.setText("Cancelar");
        jPanel5.add(btcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 100, 50));

        btregistrar.setBackground(new java.awt.Color(255, 153, 0));
        btregistrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btregistrar.setForeground(new java.awt.Color(0, 0, 0));
        btregistrar.setText("Registrar");
        btregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btregistrarActionPerformed(evt);
            }
        });
        jPanel5.add(btregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 100, 50));

        bteditar.setBackground(new java.awt.Color(255, 153, 0));
        bteditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bteditar.setForeground(new java.awt.Color(0, 0, 0));
        bteditar.setText("Editar");
        jPanel5.add(bteditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 100, 50));

        bteliminar.setBackground(new java.awt.Color(255, 153, 0));
        bteliminar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bteliminar.setForeground(new java.awt.Color(0, 0, 0));
        bteliminar.setText("Eliminar");
        jPanel5.add(bteliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 100, 50));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 600, 750));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "RESERVAS REGISTRADAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI Semilight", 1, 12))); // NOI18N
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 13)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha Entrada", "Fecha Salida", "N° Habitacion", "Tipo Habitacion", "DNI/RUC", "Cliente", "Procedencia"
            }
        ));
        tabla.setGridColor(new java.awt.Color(0, 0, 0));
        tabla.setRowHeight(30);
        tabla.setSelectionBackground(new java.awt.Color(0, 122, 255));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 680, 520));

        jLabelDNI16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelDNI16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDNI16.setText("Buscar");
        jPanel9.add(jLabelDNI16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 90, 30));

        txBuscar.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        txBuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txBuscar.setSelectionColor(new java.awt.Color(0, 122, 255));
        txBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txBuscarKeyTyped(evt);
            }
        });
        jPanel9.add(txBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 350, 30));

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 25, 700, 620));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 766, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked

    }//GEN-LAST:event_tablaMouseClicked

    private void txBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBuscarKeyReleased

    }//GEN-LAST:event_txBuscarKeyReleased

    private void txBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBuscarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txBuscarKeyTyped

    private void btregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btregistrarActionPerformed
        Crear();
    }//GEN-LAST:event_btregistrarActionPerformed

    private void lbcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbcerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_lbcerrarMouseClicked

    private void lbcerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbcerrarMouseEntered
        lbcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/cerrar2.png")));
    }//GEN-LAST:event_lbcerrarMouseEntered

    private void lbcerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbcerrarMouseExited
        lbcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/cerrar1.png")));
    }//GEN-LAST:event_lbcerrarMouseExited

    private void lbminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbminimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lbminimizarMouseClicked

    private void lbminimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbminimizarMouseEntered
        lbminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/minimizar2.png")));
    }//GEN-LAST:event_lbminimizarMouseEntered

    private void lbminimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbminimizarMouseExited
        lbminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/minimizar1.png")));
    }//GEN-LAST:event_lbminimizarMouseExited

    private void cbomaterialItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbomaterialItemStateChanged
        if (cbomaterial.getSelectedIndex() > 0) {
            StockxMat();
        }
    }//GEN-LAST:event_cbomaterialItemStateChanged
    public void StockxMat() {
        lbstock.setText(control.DevolverRegistroDto("select stock from materiales where idTipMat=(select idTipMat from tipomaterial where nomTip='" 
                + cbomaterial.getSelectedItem() + "') order by idmaterial desc limit 1;", 1));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompraMaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton bteditar;
    private javax.swing.JButton bteliminar;
    private javax.swing.JButton btregistrar;
    private javax.swing.JComboBox<String> cbocolor;
    private javax.swing.JComboBox<String> cbofacultad;
    private javax.swing.JComboBox<String> cbomarca;
    private javax.swing.JComboBox<String> cbomaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDNI16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbcerrar;
    private javax.swing.JLabel lbminimizar;
    private javax.swing.JLabel lbnomEmp;
    private javax.swing.JLabel lbstock;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txBuscar;
    private javax.swing.JTextField txtcantidad;
    // End of variables declaration//GEN-END:variables
}
