/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author ANGEL
 */
import Clases.*;
import javax.swing.JOptionPane;

public class LoginAcceso extends javax.swing.JFrame {

    /**
     * Creates new form LoginAcceso
     */
    Controlador control = new Controlador();
    String user, password;
    
    public LoginAcceso() {
        this.setUndecorated(true);
        initComponents();
        this.setTitle("Acceso al Sistema");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        l = new javax.swing.JLabel();
        txtlogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btAceder = new javax.swing.JButton();
        txtpsw = new javax.swing.JPasswordField();
        lbcerrar = new javax.swing.JLabel();
        lbminimizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(187, 187, 187));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/logounasam.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        l.setForeground(new java.awt.Color(0, 0, 0));
        l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l.setText("LOGIN:");
        jPanel2.add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 300, 30));

        txtlogin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtlogin.setForeground(new java.awt.Color(0, 0, 0));
        txtlogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 200, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PASSWORD:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 300, 30));

        btAceder.setBackground(new java.awt.Color(255, 153, 0));
        btAceder.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btAceder.setForeground(new java.awt.Color(0, 0, 0));
        btAceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/login.png"))); // NOI18N
        btAceder.setText("INGRESAR");
        btAceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcederActionPerformed(evt);
            }
        });
        jPanel2.add(btAceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 390, 150, 50));

        txtpsw.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtpsw.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtpsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 200, 30));

        lbcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/cerrar3.png"))); // NOI18N
        lbcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbcerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbcerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbcerrarMouseExited(evt);
            }
        });
        jPanel2.add(lbcerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));

        lbminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/minimizar3.png"))); // NOI18N
        lbminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbminimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbminimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbminimizarMouseExited(evt);
            }
        });
        jPanel2.add(lbminimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAcederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcederActionPerformed
        user = txtlogin.getText();
        password = txtpsw.getText();
        if (user.trim().length() != 0) {
            if (password.trim().length() != 0) {
                Login lg = new Login(user, password);
                if (lg.VerificarUsuario()) {
                    if (lg.VerificarCredenciales()) {
                        Controles.empleado = lg.getnomEmp();
                        Controles.usuario = lg.getUsuario();
                        MenuPrincipal mp = new MenuPrincipal();
                        mp.setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Credenciales incorrectas");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El usuario no existe");
                }
            } else {
                txtpsw.grabFocus();
            }
        } else {
            txtlogin.grabFocus();
        }

    }//GEN-LAST:event_btAcederActionPerformed

    private void lbminimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbminimizarMouseExited
        lbminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/minimizar3.png")));
    }//GEN-LAST:event_lbminimizarMouseExited

    private void lbminimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbminimizarMouseEntered
        lbminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/minimizar2.png")));
    }//GEN-LAST:event_lbminimizarMouseEntered

    private void lbcerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbcerrarMouseExited
        lbcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/cerrar3.png")));
    }//GEN-LAST:event_lbcerrarMouseExited

    private void lbcerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbcerrarMouseEntered
        lbcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/cerrar2.png")));
    }//GEN-LAST:event_lbcerrarMouseEntered

    private void lbcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbcerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbcerrarMouseClicked

    private void lbminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbminimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lbminimizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAcceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel l;
    private javax.swing.JLabel lbcerrar;
    private javax.swing.JLabel lbminimizar;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JPasswordField txtpsw;
    // End of variables declaration//GEN-END:variables
}
