/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Color;

/**
 *
 * @author ANGEL
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        this.setUndecorated(true);
        initComponents();
        this.setTitle("Menu Principal");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnbar1 = new javax.swing.JPanel();
        lbbar1 = new javax.swing.JLabel();
        pnbar2 = new javax.swing.JPanel();
        lbbar2 = new javax.swing.JLabel();
        pnbar3 = new javax.swing.JPanel();
        lbbar3 = new javax.swing.JLabel();
        pnbar4 = new javax.swing.JPanel();
        lbbar4 = new javax.swing.JLabel();
        lbcerrar = new javax.swing.JLabel();
        lbminimizar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txBuscar = new javax.swing.JTextField();
        btValidar1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UNASAM ADMINISTRATIVOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 40));

        pnbar1.setBackground(new java.awt.Color(0, 0, 102));
        pnbar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 255)));

        lbbar1.setBackground(new java.awt.Color(255, 255, 255));
        lbbar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbbar1.setForeground(new java.awt.Color(255, 255, 255));
        lbbar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbbar1.setText("ADMINISTRACIÓN");
        lbbar1.setToolTipText("");
        lbbar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbbar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbbar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbbar1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnbar1Layout = new javax.swing.GroupLayout(pnbar1);
        pnbar1.setLayout(pnbar1Layout);
        pnbar1Layout.setHorizontalGroup(
            pnbar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnbar1Layout.createSequentialGroup()
                .addComponent(lbbar1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnbar1Layout.setVerticalGroup(
            pnbar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnbar1Layout.createSequentialGroup()
                .addComponent(lbbar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(pnbar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 150, 40));

        pnbar2.setBackground(new java.awt.Color(0, 0, 102));
        pnbar2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 255)));

        lbbar2.setBackground(new java.awt.Color(255, 255, 255));
        lbbar2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbbar2.setForeground(new java.awt.Color(255, 255, 255));
        lbbar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbbar2.setText("COMPRA");
        lbbar2.setToolTipText("");
        lbbar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbbar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbbar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbbar2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnbar2Layout = new javax.swing.GroupLayout(pnbar2);
        pnbar2.setLayout(pnbar2Layout);
        pnbar2Layout.setHorizontalGroup(
            pnbar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnbar2Layout.createSequentialGroup()
                .addComponent(lbbar2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnbar2Layout.setVerticalGroup(
            pnbar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnbar2Layout.createSequentialGroup()
                .addComponent(lbbar2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(pnbar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 150, 40));

        pnbar3.setBackground(new java.awt.Color(0, 0, 102));
        pnbar3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 255)));

        lbbar3.setBackground(new java.awt.Color(255, 255, 255));
        lbbar3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbbar3.setForeground(new java.awt.Color(255, 255, 255));
        lbbar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbbar3.setText("ADMINISTRACIÓN");
        lbbar3.setToolTipText("");
        lbbar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbbar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbbar3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnbar3Layout = new javax.swing.GroupLayout(pnbar3);
        pnbar3.setLayout(pnbar3Layout);
        pnbar3Layout.setHorizontalGroup(
            pnbar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnbar3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbbar3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnbar3Layout.setVerticalGroup(
            pnbar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnbar3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbbar3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnbar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, -1, 40));

        pnbar4.setBackground(new java.awt.Color(0, 0, 102));
        pnbar4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 255)));

        lbbar4.setBackground(new java.awt.Color(255, 255, 255));
        lbbar4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbbar4.setForeground(new java.awt.Color(255, 255, 255));
        lbbar4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbbar4.setText("ADMINISTRACIÓN");
        lbbar4.setToolTipText("");
        lbbar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbbar4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbbar4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnbar4Layout = new javax.swing.GroupLayout(pnbar4);
        pnbar4.setLayout(pnbar4Layout);
        pnbar4Layout.setHorizontalGroup(
            pnbar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnbar4Layout.createSequentialGroup()
                .addComponent(lbbar4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnbar4Layout.setVerticalGroup(
            pnbar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnbar4Layout.createSequentialGroup()
                .addComponent(lbbar4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(pnbar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, 150, 40));

        lbcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/cerrar1.png"))); // NOI18N
        lbcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbcerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbcerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbcerrarMouseExited(evt);
            }
        });
        jPanel1.add(lbcerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1335, 5, -1, -1));

        lbminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/minimizar1.png"))); // NOI18N
        lbminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbminimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbminimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbminimizarMouseExited(evt);
            }
        });
        jPanel1.add(lbminimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1305, 5, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        jLabel8.setBackground(new java.awt.Color(255, 255, 20));
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/unasam.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(23, 23, 23));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("MENÚ PRINCIPAL");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "RESERVACIONES  PARA  HOY", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(23, 23, 23))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Reserva", "Nombre Cliente", "N° Habitacion"
            }
        ));
        tabla.setRowHeight(30);
        tabla.setSelectionBackground(new java.awt.Color(0, 122, 255));
        jScrollPane1.setViewportView(tabla);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 460, 360));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/buscar.png"))); // NOI18N
        jLabel10.setText("Buscar");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 40, 100, 30));

        txBuscar.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        txBuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txBuscar.setSelectionColor(new java.awt.Color(0, 122, 255));
        txBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txBuscarKeyReleased(evt);
            }
        });
        jPanel8.add(txBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 40, 250, 30));

        btValidar1.setBackground(new java.awt.Color(248, 177, 57));
        btValidar1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btValidar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/check.png"))); // NOI18N
        btValidar1.setText("Validar");
        btValidar1.setBorder(null);
        btValidar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btValidar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValidar1ActionPerformed(evt);
            }
        });
        jPanel8.add(btValidar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 250, 40));
        jPanel8.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 72, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBuscarKeyReleased

    }//GEN-LAST:event_txBuscarKeyReleased

    private void btValidar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValidar1ActionPerformed

    }//GEN-LAST:event_btValidar1ActionPerformed

    private void lbbar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbar1MouseEntered
        pnbar1.setBackground(Color.white);
        lbbar1.setForeground(Color.black);
    }//GEN-LAST:event_lbbar1MouseEntered

    private void lbbar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbar1MouseExited
        pnbar1.setBackground(new Color(0, 0, 102));
        lbbar1.setForeground(Color.white);
    }//GEN-LAST:event_lbbar1MouseExited

    private void lbbar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbar2MouseEntered
        pnbar2.setBackground(Color.white);
        lbbar2.setForeground(Color.black);
    }//GEN-LAST:event_lbbar2MouseEntered

    private void lbbar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbar2MouseExited
        pnbar2.setBackground(new Color(0, 0, 102));
        lbbar2.setForeground(Color.white);
    }//GEN-LAST:event_lbbar2MouseExited

    private void lbbar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbar3MouseEntered
        pnbar3.setBackground(Color.white);
        lbbar3.setForeground(Color.black);
    }//GEN-LAST:event_lbbar3MouseEntered

    private void lbbar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbar3MouseExited
        pnbar3.setBackground(new Color(0, 0, 102));
        lbbar3.setForeground(Color.white);
    }//GEN-LAST:event_lbbar3MouseExited

    private void lbbar4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbar4MouseEntered
        pnbar4.setBackground(Color.white);
        lbbar4.setForeground(Color.black);
    }//GEN-LAST:event_lbbar4MouseEntered

    private void lbbar4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbar4MouseExited
        pnbar4.setBackground(new Color(0, 0, 102));
        lbbar4.setForeground(Color.white);
    }//GEN-LAST:event_lbbar4MouseExited

    private void lbbar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbar2MouseClicked
       CompraMaterial cm=new CompraMaterial();
       cm.setVisible(true);
    }//GEN-LAST:event_lbbar2MouseClicked

    private void lbbar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbar1MouseClicked
        Trabajadores tr = new Trabajadores();
        tr.setVisible(true);
    }//GEN-LAST:event_lbbar1MouseClicked

    private void lbminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbminimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lbminimizarMouseClicked

    private void lbminimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbminimizarMouseEntered
        lbminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/minimizar2.png")));
    }//GEN-LAST:event_lbminimizarMouseEntered

    private void lbminimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbminimizarMouseExited
        lbminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/minimizar1.png")));
    }//GEN-LAST:event_lbminimizarMouseExited

    private void lbcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbcerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbcerrarMouseClicked

    private void lbcerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbcerrarMouseEntered
        lbcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/cerrar2.png")));
    }//GEN-LAST:event_lbcerrarMouseEntered

    private void lbcerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbcerrarMouseExited
        lbcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/cerrar1.png")));
    }//GEN-LAST:event_lbcerrarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btValidar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbbar1;
    private javax.swing.JLabel lbbar2;
    private javax.swing.JLabel lbbar3;
    private javax.swing.JLabel lbbar4;
    private javax.swing.JLabel lbcerrar;
    private javax.swing.JLabel lbminimizar;
    private javax.swing.JPanel pnbar1;
    private javax.swing.JPanel pnbar2;
    private javax.swing.JPanel pnbar3;
    private javax.swing.JPanel pnbar4;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txBuscar;
    // End of variables declaration//GEN-END:variables
}
